use leoAutoras;

INSERT INTO author (name, surname, country, birthdate, deathdate, bio)
VALUES	
('Louisa', 'May Alcott', 'Estados Unidos', '1832-11-29', '1888-03-06', 'Louisa May Alcott fue una escritora estadounidense conocida principalmente por su novela "Mujercitas". Nacida en Germantown, Pensilvania, Alcott creció en Massachusetts y comenzó su carrera como escritora a una edad temprana. Escribió numerosos libros y cuentos, muchos de los cuales estaban inspirados en sus propias experiencias. La obra de Alcott exploraba temas de familia, feminismo y cuestiones sociales, convirtiéndola en una de las autoras más populares e influyentes de su tiempo.'),
('Harper', 'Lee', 'Estados Unidos', '1926-04-28', '2016-02-19', 'Harper Lee fue una autora estadounidense conocida por su novela "Matar a un ruiseñor". Nacida en Monroeville, Alabama, Lee se inspiró en sus propias experiencias de la infancia en el Sur profundo de Estados Unidos. "Matar a un ruiseñor" se convirtió en un clásico instantáneo, explorando temas de injusticia racial y la pérdida de la inocencia. Lee recibió numerosos premios por su obra, y su novela sigue siendo ampliamente estudiada y admirada por su poderosa narrativa y su comentario social.'),
('Jane', 'Austen', 'Reino Unido', '1775-12-16', '1817-07-18',  'Jane Austen fue una novelista inglesa conocida por sus ingeniosas e perspicaces retratos de la vida de la alta sociedad británica. Nacida en Steventon, Hampshire, las obras de Austen, como "Orgullo y prejuicio", "Sentido y sensibilidad" y "Emma", son consideradas clásicos literarios y han sido adaptadas en numerosas películas y series de televisión. Las novelas de Austen examinan las relaciones sociales y románticas de su época y ofrecen una aguda crítica de las normas y expectativas sociales impuestas a las mujeres.'),
('Ana', 'Frank', 'Alemania', '1929-06-12', '1945-02-01',  'Ana Frank fue una escritora alemana de origen judío, conocida por su famoso diario "El diario de Ana Frank". Nació en Fráncfort del Meno, Alemania, y se mudó a Ámsterdam, Países Bajos, durante la Segunda Guerra Mundial. Ana y su familia se escondieron en un ático secreto durante más de dos años para evitar la persecución nazi. Su diario, publicado después de su muerte, se convirtió en un testimonio conmovedor de los horrores del Holocausto y ha sido leído y estudiado en todo el mundo.'),
('Suzanne', 'Collins', 'Estados Unidos', '1962-08-10', null ,  'Suzanne Collins es una autora estadounidense conocida por su exitosa trilogía de literatura juvenil "Los juegos del hambre". Nacida en Hartford, Connecticut, Collins trabajó en televisión y literatura infantil antes de alcanzar reconocimiento internacional con la serie "Los juegos del hambre". Las novelas, ambientadas en un futuro distópico, cuentan la historia de Katniss Everdeen mientras lucha contra un gobierno tiránico. Los libros de Collins han sido adaptados en exitosas películas y han generado discusiones sobre temas de poder, desigualdad y supervivencia.'),
('Charlotte', 'Brontë', 'Reino Unido', '1816-04-21', '1855-03-31',  'Charlotte Brontë fue una novelista y poetisa inglesa, conocida principalmente por su novela "Jane Eyre". Nacida en Thornton, West Yorkshire, Brontë y sus hermanas Emily y Anne fueron celebradas escritoras del siglo XIX. "Jane Eyre", una historia sobre el viaje de autodescubrimiento de una joven institutriz, es considerada un clásico de la literatura inglesa. Las obras de Brontë desafiaron las convenciones victorianas y exploraron temas de desigualdad de género, amor e independencia.'),
('Carmen', 'Laforet', 'España', '1921-09-06', '2044-02-28',  'Carmen Laforet fue una autora española conocida por su novela debut "Nada". Nacida en Barcelona, la novela de Laforet, publicada en 1944, recibió aclamación crítica y ganó el Premio Nadal, uno de los premios literarios más prestigiosos de España. "Nada" explora el período de posguerra en España y retrata las luchas de la protagonista, Andrea, mientras navega por una sociedad sombría y opresiva. La obra de Laforet se considera una contribución significativa a la literatura española y al movimiento literario conocido como "la Generación del "50".');

SELECT * FROM author;